sudo: false
dist: trusty
language: rust

install:
- rustup component add rustfmt clippy
- rustup target add wasm32-unknown-unknown
- cargo install -f grcov

env:
  global:
  - CARGO_INCREMENTAL=0
  - RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

script:
- cargo build --all-features --verbose $CARGO_OPTIONS 
- cargo test --all-features --verbose $CARGO_OPTIONS
- ./coverage.sh
- cargo clippy --all-features --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --no-deps

after_success:
- bash <(curl -s https://codecov.io/bash) -f lcov.info
