sudo: false
dist: trusty
language: generic

env:
  global:
  - CARGO_INCREMENTAL=0
  - RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

jobs:
  include:
    - stage: "Test"
      name: "Server"
      language: rust
      install:
      - rustup component add rustfmt clippy
      - rustup target add wasm32-unknown-unknown
      - cargo install -f grcov
      script: ./ci/test_server.sh

    - stage: "Test"
      name: "Client"
      script: ./ci/test_client.sh
      python:
        - 3.7
      node_js:
        - node

after_success:
- bash <(curl -s https://codecov.io/bash) -f lcov.info
