[[items]]
name = "Casein"
alternative_names = []
state = "carnist"
description = """
A family of proteins found in dairy milk resposible the strechiness typically associated with melted cheese.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/casein/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Casein" },
    { type = "url", value = "https://itdoesnttastelikechicken.com/melty-stretchy-gooey-vegan-mozarella/" }
]
vegan_alternatives = ["Tapioca Starch"]

[[items]]
name = "Whey"
alternative_names = []
state = "carnist"
description = """
The liquid that remains after dairy milk has been curdled and strained.
A by-product of the cheese industry found in surprisingly many otherwise vegan foods.
Often found in protein shakes.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/whey/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Whey" },
    { type = "url", value = "https://www.bodybuilding.com/fun/10-best-tasting-vegan-protein-powders.html" }
]
vegan_alternatives = ["Pea Protein", "Rice Protein"]

[[items]]
name = "Lactose"
alternative_names = [
    "Milk sugar"
]
state = "carnist"
description = """
A sugar found in dairy milk. About 65% of the global population are lactose intolerant,
which pushes the market to produce a wide variety of dairy-free products.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/dairy-free/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Lactose" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Lactose_intolerance" }
]
vegan_alternatives = []

[[items]]
name = "Cholesterol"
alternative_names = [
    "Cholesterin",
    "Cholesteryl alcohol"
]
state = "carnist"
description = """
Cholesterol is produced in an animal's liver.
"""
sources = [
    { type = "url", value = "https://en.wikipedia.org/wiki/Cholesterol" }
]
vegan_alternatives = []

[[items]]
name = "Confectioner's Glaze"
alternative_names = [
    "Pharmaceutical glaze",
    "Resinous glaze",
    "Pure food glaze",
    "Natural glaze",
    "Confectioner's resin"
]
state = "carnist"
description = """
Confectioner's glaze is an alcohol based solution containing shellac,
which is a resin secreted by the female lac bug when building a cocoon.
"""
sources = [
    { type = "url", value = "https://en.wikipedia.org/wiki/Pharmaceutical_glaze" }
]
vegan_alternatives = []

[[items]]
name = "Castoreum"
alternative_names = [
]
state = "carnist"
description = """
This tincture used in some perfumes is a yellowish secretion from the castor sacs of beavers.
The animals use these to mark their territory due to its strong leather-like smell.
In order to harvest the Castoreum, the sacs are cut off from killed beavers and left to dry for two or more years.
"""
sources = [
    { type = "url", value = "https://en.wikipedia.org/wiki/Castoreum" }
]
vegan_alternatives = [ "castor oil" ]

[[items]]
name = "Castor Oil"
alternative_names = [
]
state = "vegan"
description = """
Not to be confused with the carnist castoreum, castor oil is pressed from castor beans.
"""
sources = [
    { type = "url", value = "https://en.wikipedia.org/wiki/Castor_oil" }
]
vegan_alternatives = [ ]
