name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
      - name: Run Tests
        run: ./ci/test_server.sh
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
  client:
    name: Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
