name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
      - name: Run tests
        run: ./ci/test_server.sh